[book]
title = "Lush Docs"
authors = ["yrwq"]
language = "en"
description = "Documentation for configuring and extending Lush."
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/yrwq/lush"
edit-url-template = "https://github.com/yrwq/lush/edit/main/docs/{path}"
additional-css = ["theme/gruvbox.css"]
